# Generated by Django 5.2.3 on 2025-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('creator', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('ON', 'On Going'), ('C', 'Completed')], default='NS', max_length=255)),
                ('first_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
