# Generated by Django 5.2.3 on 2025-07-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
